name: Build and Push Docker Image

on:
  push:
    branches:
    - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-west-1
      ECR_REGISTRY: ECR_REGISTRY

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

    - name: Build and Push Docker Image
      run: |
        docker build -t frontend-test .
        docker tag frontend-test:latest $ECR_REGISTRY:latest
        docker push $ECR_REGISTRY:latest
